# Hadolint configuration
# https://github.com/hadolint/hadolint

ignored:
  # Allow apt-get install without version pinning (we use slim base)
  - DL3008
  # Allow pip install without version pinning (versions in requirements.txt)
  - DL3013

trustedRegistries:
  - docker.io
  - python

failure-threshold: warning
